# Generated by Django 4.1.6 on 2023-02-16 11:06

import ckeditor.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsweb',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temeHome', models.CharField(max_length=25555)),
                ('temasport', models.CharField(max_length=25555)),
                ('tematecnology', models.CharField(max_length=25555)),
                ('temabusines', models.CharField(max_length=25555)),
                ('temapolitic', models.CharField(max_length=25555)),
                ('temahealth', models.CharField(max_length=25555)),
                ('link', models.CharField(max_length=255)),
                ('photo', models.ImageField(null=True, upload_to='photo/%Y/%m/%d')),
                ('home', ckeditor.fields.RichTextField()),
                ('sportnNew', ckeditor.fields.RichTextField()),
                ('tecnologyNews', ckeditor.fields.RichTextField()),
                ('businessnews', ckeditor.fields.RichTextField()),
                ('politikNews', ckeditor.fields.RichTextField()),
                ('healthNews', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
