 # Generated by Django 4.1.6 on 2023-02-16 11:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsweb',
            name='newNews',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
